name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  tests:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: soap, mbstring, xml, ctype, iconv
          coverage: none
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer update --prefer-dist --no-progress --no-interaction

      - name: Check Code Style (PHP CS Fixer)
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Static Analysis (PHPStan)
        run: vendor/bin/phpstan analyse --no-progress

      - name: Run Tests (PHPUnit)
        run: vendor/bin/phpunit tests/
